var glosbe_lang_array = [
    {"code":"af", "name": "Afrikaans"},
    {"code":"sq", "name": "Albanian"},
    {"code":"xno", "name": "Anglo-Norman"},
    {"code":"ar", "name": "Arabic"},
    {"code":"an", "name": "Aragonese"},
    {"code":"hy", "name": "Armenian"},
    {"code":"ast", "name": "Asturian"},
    {"code":"az", "name": "Azerbaijani"},
    {"code":"eu", "name": "Basque"},
    {"code":"bar", "name": "Bavarian"},
    {"code":"be", "name": "Belarusian"},
    {"code":"bn", "name": "Bengali"},
    {"code":"bs", "name": "Bosnian"},
    {"code":"br", "name": "Breton"},
    {"code":"bg", "name": "Bulgarian"},
    {"code":"my", "name": "Burmese"},
    {"code":"ca", "name": "Catalan"},
    {"code":"zh", "name": "Chinese"},
    {"code":"swh", "name": "Coastal Swahili"},
    {"code":"crh", "name": "Crimean Turkish"},
    {"code":"hr", "name": "Croatian"},
    {"code":"cs", "name": "Czech"},
    {"code":"da", "name": "Danish"},
    {"code":"nl", "name": "Dutch"},
    {"code":"en", "name": "English"},
    {"code":"eo", "name": "Esperanto"},
    {"code":"et", "name": "Estonian"},
    {"code":"fo", "name": "Faroese"},
    {"code":"fil", "name": "Filipino"},
    {"code":"fi", "name": "Finnish"},
    {"code":"fr", "name": "French"},
    {"code":"gl", "name": "Galician"},
    {"code":"ka", "name": "Georgian"},
    {"code":"de", "name": "German"},
    {"code":"el", "name": "Greek"},
    {"code":"gu", "name": "Gujarati"},
    {"code":"ht", "name": "Haitian"},
    {"code":"haw", "name": "Hawaiian"},
    {"code":"he", "name": "Hebrew"},
    {"code":"hil", "name": "Hiligaynon"},
    {"code":"hi", "name": "Hindi"},
    {"code":"hu", "name": "Hungarian"},
    {"code":"is", "name": "Icelandic"},
    {"code":"io", "name": "Ido"},
    {"code":"id", "name": "Indonesian"},
    {"code":"ia", "name": "Interlingua"},
    {"code":"pes", "name": "Iranian Persian"},
    {"code":"ga", "name": "Irish"},
    {"code":"it", "name": "Italian"},
    {"code":"ja", "name": "Japanese"},
    {"code":"krc", "name": "Karachay-Balkar"},
    {"code":"kk", "name": "Kazakh"},
    {"code":"kha", "name": "Khasi"},
    {"code":"km", "name": "Khmer"},
    {"code":"ko", "name": "Korean"},
    {"code":"ses", "name": "Koyraboro Senni"},
    {"code":"ku", "name": "Kurdish"},
    {"code":"lo", "name": "Lao"},
    {"code":"la", "name": "Latin"},
    {"code":"lv", "name": "Latvian"},
    {"code":"li", "name": "Limburgish"},
    {"code":"lt", "name": "Lithuanian"},
    {"code":"nds", "name": "Low German"},
    {"code":"lb", "name": "Luxembourgish"},
    {"code":"mk", "name": "Macedonian"},
    {"code":"ms", "name": "Malay"},
    {"code":"ml", "name": "Malayalam"},
    {"code":"mt", "name": "Maltese"},
    {"code":"cmn", "name": "Mandarin"},
    {"code":"gv", "name": "Manx"},
    {"code":"mr", "name": "Marathi"},
    {"code":"frm", "name": "Middle French"},
    {"code":"nan", "name": "Min Nan Chinese"},
    {"code":"mn", "name": "Mongolian"},
    {"code":"nv", "name": "Navajo"},
    {"code":"nap", "name": "Neapolitan"},
    {"code":"se", "name": "Northern Sami"},
    {"code":"nb", "name": "Norwegian"},
    {"code":"nov", "name": "Novial"},
    {"code":"oc", "name": "Occitan"},
    {"code":"ang", "name": "Old English"},
    {"code":"fro", "name": "Old French"},
    {"code":"non", "name": "Old Norse"},
    {"code":"pap", "name": "Papiamento"},
    {"code":"fa", "name": "Persian"},
    {"code":"pms", "name": "Piemontese"},
    {"code":"pl", "name": "Polish"},
    {"code":"pt", "name": "Portuguese"},
    {"code":"ro", "name": "Romanian"},
    {"code":"rm", "name": "Romansh"},
    {"code":"rom", "name": "Romany"},
    {"code":"ru", "name": "Russian"},
    {"code":"sa", "name": "Sanskrit"},
    {"code":"sco", "name": "Scots"},
    {"code":"gd", "name": "Scottish Gaelic"},
    {"code":"sr", "name": "Serbian"},
    {"code":"sh", "name": "Serbo Croatian"},
    {"code":"scn", "name": "Sicilian"},
    {"code":"sk", "name": "Slovak"},
    {"code":"sl", "name": "Slovenian"},
    {"code":"azb", "name": "South Azerbaijani"},
    {"code":"es", "name": "Spanish"},
    {"code":"arb", "name": "Standard Arabic"},
    {"code":"sw", "name": "Swahili"},
    {"code":"sv", "name": "Swedish"},
    {"code":"tl", "name": "Tagalog"},
    {"code":"tg", "name": "Tajik"},
    {"code":"ta", "name": "Tamil"},
    {"code":"tt", "name": "Tatar"},
    {"code":"te", "name": "Telugu"},
    {"code":"th", "name": "Thai"},
    {"code":"tr", "name": "Turkish"},
    {"code":"tk", "name": "Turkmen"},
    {"code":"uk", "name": "Ukrainian"},
    {"code":"ur", "name": "Urdu"},
    {"code":"uz", "name": "Uzbek"},
    {"code":"vec", "name": "Venetian"},
    {"code":"vi", "name": "Vietnamese"},
    {"code":"vo", "name": "Volapük"},
    {"code":"cy", "name": "Welsh"},
    {"code":"fy", "name": "Western Frisian"},
    {"code":"wym", "name": "Wymysorys"},
    {"code":"yi", "name": "Yiddish"},
    {"code":"yo", "name": "Yoruba"},
    {"code":"yua", "name": "Yucateco"},
    {"code":"zu", "name": "Zulu"},
];
